# Generated by Django 4.1.4 on 2023-01-19 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.doctor"
            ),
        ),
    ]
